### ISSUE TITLE
OpenBSD 7.4 - 24 errors

### ISSUE THREAD

**Issue by jezcaudle** [dotpy/py-pf#16] opened 2023-12-06 17:13 UTC
I've tried installing via:

pkg_add py3-py

and also using the git clone as per your readme and the tests give 24 errors.

They are all [Errno 13] Permission denied

I'm not sure if I'm doing something wrong, pf is enabled and running.

**Comment by dotpy** [comment] 2023-12-07 21:10
Hi,

I'm sorry, this package hasn't been actively maintained for some time, so the errors you're getting must definitely be caused by code being obsolete.

I thought there wasn't much interest in this package anymore, but if you think it could be useful to you, I'll be glad to fix it as soon as possible. I'll get back to you in a few days!

Best regards!

**Comment by jezcaudle** [comment] 2023-12-08 10:17
That would be great - thanks.

**Comment by dotpy** [comment] 2023-12-22 21:52
Hi @jezcaudle,
I've just committed a new version of py-pf, updated to OpenBSD 7.4.
You can install it with `python3 setup.py install` or from pypi.
Please let me know if you have any issues with it.
Cheers!

**Closed by dotpy** 2023-12-22 21:52 UTC

**Comment by jezcaudle** [comment] 2024-01-08 11:02
Tested and it's working. Thank you very much.
